; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
build_flags = 
	-D TEENSY_OPT_SMALLEST_CODE_LTO
build_src_flags = 
	-std=gnu++20
	-Wall
	-Wextra
	-Wpedantic
	-Wshadow
	-Wdouble-promotion
	-Wundef
	-ffunction-sections
	-fdata-sections
	-fno-exceptions
	-fno-rtti
	-Wl,-Map=output.map
extra_scripts = 
	RemoveLibWarnings.py
	pre:Compiledb.py
lib_deps = 
	hideakitai/ArduinoEigen@^0.3.2
	adafruit/Adafruit BMP280 Library@^2.6.8
	adafruit/Adafruit LIS3MDL@^1.2.4
	adafruit/Adafruit LSM6DS@^4.7.4
	adafruit/Adafruit MCP9808 Library@^2.0.2
	adafruit/Adafruit GPS Library@^1.7.5
	git@github.com:adafruit/RadioHead.git
