; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
build_flags = 
	-D TEENSY_OPT_SMALLEST_CODE_LTO
	-D WORK_QUEUE_PREEMPTIVE=0
	-D USST_PLATFORM_ARDUINO

build_src_flags = 
	-std=gnu++20
	-Wall
	-Wextra
	-Wpedantic
	-Wshadow
	-Wdouble-promotion
	-Wundef
	-ffunction-sections
	-fdata-sections
	-fno-exceptions
	-fno-rtti
	-Wl,-Map=output.map

custom_nanopb_protos =
	+<lib/Tisdale/**/*.proto>
custom_nanopb_options =
	--source-extension=.cpp 
	--cpp-descriptors

extra_scripts =
	pre:Compiledb.py
	RemoveLibWarnings.py

lib_deps = 
	hideakitai/ArduinoEigen
	git@github.com:tonton81/WDT_T4.git
	git@github.com:USSTRocketry/Turtleford.git
	git@github.com:USSTRocketry/Carrot-River.git
	git@github.com:USSTRocketry/HAL.git
